name: Frontend tests

on:
  push:
    paths:
      - '.github/**'
      - 'frontend/**'
    pull_request:
      branches:
        - master
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - run: ls -l
      working-directory: ${{env.working-directory}}

    - name: npm version
      run: npm -v

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Run lint
      run: npm run lint
      working-directory: ${{env.working-directory}}

    - name: Run tests
      run: npm run test-headless
      working-directory: ${{env.working-directory}}

